"$schema" = 'https://starship.rs/config-schema.json'

format = """$os$username$directory$git_branch$fill$nodejs$python$time
[ ](bold)"""
palette = "catppuccin_mocha"
add_newline = false

[os]
style = "bold"
disabled = false
symbols = { Macos = " ", Ubuntu = " " }

[username]
style_user = "bold mauve"
disabled = false
show_always = true

[directory]
truncation_length = 5
truncate_to_repo = true
style = "bold blue"

[git_branch]
style = "bold teal"

[fill]
symbol = " "

[python]
symbol = " "
style = "bold yellow"

[nodejs]
style = "bold green"

[time]
format = "󰥔 [$time]($style) "
disabled = true
style = "bold"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
