require "plugins.install"

require "plugins.catppuccin"
require "plugins.mason"
require "plugins.treesitter"
require "plugins.conform"
require "plugins.snacks"
require "plugins.copilot"
require "plugins.opencode"
require "plugins.blink"
require "plugins.oil"
require "plugins.git"
require "plugins.dap"
require "plugins.ui"
require "plugins.markdown"
require "plugins.qol"
